### ISSUE TITLE
Consider using KISS as default library in examples

### ISSUE THREAD

**Issue by cibomahto** [kylemcdonald/ofxFft#15]
The examples are all configured to use FFTW by default, which means that they won't compile of the of the box. Configuring them to work as KISS FFT would make the experience smoother.

This would be pretty non-invasive and just involves changing which implementation is commented out by default. If it sounds good, I'm happy to make the changes.

**Comment by kylemcdonald** [comment]
This sounds great to me! Please send a PR when you get the chance.

**Comment by danomatika** [comment]
I have this mostly implemented in my PR. I'll do a quick check now.

**Comment by danomatika** [comment]
Ok, all good to go now in #9. BASIC is the default in the examples so they work out of the box after you generated them with the OF ProjectGenerator.

**Comment by danomatika** [comment]
Merged in master, so this can be closed.
